import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/nav";
import { Separator } from "@/components/ui/separator";
import Link from "next/link";
import { Fira_Sans } from "next/font/google";

const fira = Fira_Sans({
  subsets: ["latin"],
  weight: "500",
});



const poppins = Poppins({
  subsets: ["latin"],
  weight: "500",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="px-52">
      <body
        className={`${fira.className} bg-zinc-900 flex flex-col h-screen justify-between py-10`}
      >
        <Navbar />
        {children}
        <Separator className="my-4 text-zinc-200" />
        <div className="flex justify-around">
          <div className="flex flex-col gap-2">
            <Link
              target="_blank"
              className="text-zinc-100 text-sm hover:text-zinc-400 hover:underline underline-offset-4 transition-all"
              href="https://www.linkedin.com/in/mnikel/"
            >
              Linkedin
            </Link>
            <Link
              target="_blank"
              className="text-zinc-100 text-sm hover:text-zinc-400 hover:underline underline-offset-4 transition-all"
              href="https://www.github.com/marcossnikel"
            >
              Github
            </Link>
          </div>
          <div className="flex flex-col gap-2">
            <Link
              target="_blank"
              className="text-zinc-100 text-sm hover:text-zinc-400 hover:underline underline-offset-4 transition-all"
              href="https://twitter.com/marcosnikeldev"
            >
              Twitter
            </Link>
            <Link
              className="text-zinc-100 text-sm hover:text-zinc-400 hover:underline  underline-offset-4 transition-all"
              href="/contact"
            >
              Contact
            </Link>
          </div>
        </div>
      </body>
    </html>
  );
}
